# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9f00e01eb014dbc35e892411646d788b7a0c54f3c9f87c9016881f957daa8e0080886c4296382ece0ada7a7410623cbfca710e323fd7aba1bc5434f1d258ba5c

test:
  secret_key_base: d68840a5e06c4c5805d5f8dd5e8f341feab484722623b80a092484f0af74a37abb9caa09fa8508de8f18c521f37321064447f6be661389adf20c794361837467

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
